---
- name: Check configuration
  shell: " {{ vmagent_check_command }}"
  register: result
  retries: 3
  delay: 3
  until: result is not failed

- name: Reload vmagent
  community.docker.docker_container:
    name: "{{ vmagent_container_name }}"
    state: started
    restart: true
  retries: 3
  delay: 3
